### ISSUE TITLE
visual studio code does not recognize fasthtml import

### ISSUE THREAD

**Issue by alturuca** [AnswerDotAI/fasthtml#241] opened 2024-08-10 16:18 UTC
when the first line is written from fasthtml.common import * it reports an error
![Captura de pantalla 2024-08-10 111726](https://github.com/user-attachments/assets/652d624d-2fb9-4209-93f4-b37e7ac54234)

**Comment by alturuca** [comment] 2024-08-10 16:19
fasthtml is already installed

**Comment by palomino79** [comment] 2024-08-10 16:58
@alturuca This issue is likely caused by having the wrong interpreter selected with VSCode. To further diagnose, I would suggest checking to see which interpreter is currently selected as the default python interpreter. You can see this easily by going to View > Command Palette > and typing "Python: Select Interpreter." Selecting that option should show you a highlighted interpreter path that indicates where VSCode is looking for the python interpreter it wants to use. If the interpreter points to the interpreter you expect, I would suggest

1. Running `pip freeze`, and seeing if the command shows python-fasthtml is installed. And, if it is,
2. Executing the file with `python alex.py` to see if it produces an import error. If it doesn't, then,
3. Try closing VSCode and restarting it, as the issue likely lies with the IDE's environment detection mechanism, and not with the python path.

If VSCode does not point to the expected interpreter path, then enter that path and it should work.

**Closed** 2024-08-11 08:06 UTC
