### ISSUE TITLE
No attribute 'canvas_data'

### ISSUE THREAD

**Issue by willhpkns** [AnswerDotAI/fasthtml#141] opened 2024-08-01 07:54 UTC
Received Error: AttributeError: 'Items' object has no attribute 'canvas_data'

Tried to run the "Saving and Loading Canvases" from the JS App walkthrough (QuickDraw: A FastHTML Adventure 🎨✨
) by copying directly but received the above error.

**Comment by willhpkns** [comment] 2024-08-01 08:05
Works if replaced with 

app = FastHTML()
rt = app.route
db = database('data/drawapp.db')
rooms = db.t.rooms
if rooms not in db.t:
    rooms.create(id=int, name=str, created_at=str, canvas_data=str, pk='id')
Room = rooms.dataclass()

**Comment by ncoop57** [comment] 2024-08-01 17:41
Hmmm, I wonder if the issue is because when the initial db is created the first set of rooms won't have that field and then when you go to that step in the tutorial it fails with some rooms not being updated. Could you try deleting the `data/drawapp.db` and then re running the `fast_app` function version and seeing if you get the same error? If that works, I can update the docs to ensure people nuke the db before proceeding.

**Comment by jph00** [comment] 2024-08-03 04:48
> If that works, I can update the docs to ensure people nuke the db before proceeding.

Might be a good idea. Currently we don't auto-transform the DB if there's changes. (Although that would be a nice feature to add.)

**Comment by jph00** [comment] 2024-08-04 21:49
@ncoop57 maybe you can try this if you have a moment?

**Comment by ncoop57** [comment] 2024-08-05 13:38
Yeah, I'll look into some ways we can handle this. The minimum I think will be just letting the user know. Next if it is simply a new field doing it automatically. However, for removing a field, we probably just need to throw an exception or unless they specify a flag to delete the column

**Comment by ncoop57** [comment] 2024-08-05 20:17
Working on a fix in #202

**Comment by ncoop57** [comment] 2024-08-07 14:17
Should be fixed now from #202

**Closed** 2024-08-07 14:17 UTC
